config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "welcome#index"

  resources :users, except: [:index, :edit]

  resources :projects do
    resources :bids end

  resources :sessions, only: [:new, :create, :destroy]

  patch "/bids/:id/complete", to: "bids#complete"
  patch "/projects/:id/completeclient", to: "projects#completeclient"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#dashboard"
  # get "/accounts", to: "users#show"
  get "/accounts/edit", to: "users#edit"
  get "/vendors", to: "users#index"
  get "/contact", to: "welcome#contact"
  # get "/vendor/:id", to: "users#show"

  # get "/jobs", to: "jobs#index"

end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :project
  belongs_to :user

  def find_project
    Project.find(project_id)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def show
    @bid = Bid.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @bid = Bid.new
  end

  def create
    @bid = Bid.new(bid_params)
    @bid.project_id = params[:project_id]
    @bid.user_id = current_user.id
    @bid.f_name = current_user.f_name
    @bid.l_name = current_user.l_name
    if @bid.save
      redirect_to projects_path
      flash[:notice] = "Sent bid to client!"
    else
      render :new
      flash[:alert] = "Incomplete fields."
    end
  end

  def edit
    @bid = Bid.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  def update
    @bid = Bid.find(params[:id])
    if @bid.update_attributes(bid_params)

      redirect_to project_path(@bid.project)
    else
      render :edit
    end
  end

  def complete
    @bid = Bid.find(params[:id])
    @project = @bid.project
    @bid.accepted = true
    @project.accepted_bid_id = @bid.id
    @project.assigned = true
    @project.vendor_id = @bid.user_id
    if @bid.save(validate: false) && @bid.project.save(validate: false)
      flash[:notice] = "Bid accepted!"
      redirect_to dashboard_path
    else
      redirect_to project_path(@project)
    end
  end

  def destroy
    @bid = Bid.find(params[:id])
    @project = @bid.project
    @bid.destroy
    redirect_to project_path(@project)
  end

private

  def bid_params
    params.require(:bid).permit(:budget, :delivery_date, :message)
  end

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/edit.html.erb
<% if @bid.user_id == current_user.id %>
<div class="container">
  <h2>Edit your bid on <%= @project.name %></h2>
</div>
<div class="custom-notice"><%= notice %></div>

<div class="container">
  <h4>
    <%= @project.user.f_name %> <%= @project.user.l_name %>'s Proposal
  </h4>
  <div class="row">
    <div class="col-xs-3 field">
      <strong>Language Combination: </strong>
    </div>
    <div class="col-xs-6 field">
      <%= @project.language_1 %> to <%= @project.language_2 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <strong>Word Count: </strong>
    </div>
    <div class="col-xs-6 field">
      <%= @project.word_count %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <strong>Proposed budget: </strong>
    </div>
    <div class="col-xs-6 field">
      <%= @project.budget %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <strong>Proposed delivery date: </strong>
    </div>
    <div class="col-xs-6 field">
      <%= @project.delivery_date %>
    </div>
  </div>
</div>

<div class="container">
  <h4>Your Bid</h4>
<%= form_for @bid, url: project_bid_path(@project, @bid) do |f| %>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "Proposed budget: " %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :budget, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "Proposed delivery date: " %>
    </div>
    <div class="col-xs-6 field">
      <%= f.date_select :delivery_date, :order => [:month, :day, :year] %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "Message: " %>
    </div>
    <div class="col-xs-6 field">
      <%= f.text_area :message %>
    </div>
  </div>
  <div class="actions">
  <%= f.submit "Update Bid", class: "btn btn-success" %>
  <%= link_to "Delete Bid", project_bid_path(@project, @bid), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>
  </div>

</div>
<% end %>
<% end %>

app/views/bids/new.html.erb
<h2>Bid on <%= @project.name %></h2>

<div class="custom-notice"><%= notice %></div>

<div class="container">
  <h4>
    <%= @project.user.f_name %> <%= @project.user.l_name %>'s Proposal</h4>
  <div class="row">
    <div class="col-xs-3 field">
      <strong>Language Combination: </strong>
    </div>
    <div class="col-xs-6 field text-left">
      <%= @project.language_1 %> to <%= @project.language_2 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <strong>Word Count: </strong>
    </div>
    <div class="col-xs-6 field text-left">
      <%= @project.word_count %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <strong>Proposed budget: </strong>
    </div>
    <div class="col-xs-6 field text-left">
      <%= @project.budget %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <strong>Proposed delivery date: </strong>
    </div>
    <div class="col-xs-6 field text-left">
      <%= @project.delivery_date %>
    </div>
  </div>
</div>

<div class="container">
  <h4>Your Bid</h4>
<%= form_for @bid, url: project_bids_path(@project, @bid) do |f| %>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "Proposed budget: " %>
    </div>
    <div class="col-xs-6 field text-left">
      <%= f.number_field :budget, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "Proposed delivery date: " %>
    </div>
    <div class="col-xs-6 field text-left">
      <%= f.date_select :delivery_date, :order => [:month, :day, :year] %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "Message: " %>
    </div>
    <div class="col-xs-6 field text-left">
      <%= f.text_area :message %>
    </div>
  </div>
<div class="actions"><%= f.submit "Make Bid", class: "btn btn-success" %></div>
<% end %>
</div>

app/views/bids/show.html.erb
This is the bid show page.