config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "welcome#index"

  resources :users, except: [:index, :edit]

  resources :projects do
    resources :bids end

  resources :sessions, only: [:new, :create, :destroy]

  patch "/bids/:id/complete", to: "bids#complete"
  patch "/projects/:id/completeclient", to: "projects#completeclient"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#dashboard"
  # get "/accounts", to: "users#show"
  get "/accounts/edit", to: "users#edit"
  get "/vendors", to: "users#index"
  get "/contact", to: "welcome#contact"
  # get "/vendor/:id", to: "users#show"

  # get "/jobs", to: "jobs#index"

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :projects, dependent: :destroy
  has_many :bids, dependent: :destroy

  has_attached_file :avatar, styles: { thumb: "150x150#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :password, length: {minimum: 6, maximum: 20}
  validates :email, presence: true, uniqueness: true

  def ata_certified?
    "yes" if judicial_court else "no"
  end

  def judicial_court?
    "yes" if judicial_court else "no"
  end

  def trados?
    "yes, " + trados_version if trados else "no"
  end

  def available?
    "yes" if available else "no"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, except: [:new, :create]

  def index
    @users = User.all
  end

  def dashboard
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to FOLIO! You've successfully signed up.
        Please complete your profile below, and then you can get started."
      redirect_to accounts_edit_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to dashboard_path
      flash[:notice] = "Success!"
    else
      redirect_to accounts_edit_path
      flash[:notice] = "Incomplete fields."
    end
  end

private

  def user_params
    params.require(:user).permit(
      :ata_certified,
      :available,
      :bio,
      :city,
      :company,
      :country,
      :email,
      :f_name,
      :is_client,
      :is_graphic_designer,
      :is_transcriber,
      :is_translator,
      :judicial_court,
      :l_name,
      :language_1,
      :language_2,
      :message,
      :minimum_rate,
      :notary_fee,
      :password,
      :password_confirmation,
      :phone_number,
      :position,
      :rate_per_minute,
      :rate_per_word,
      :rate_per_work_hour,
      :rush_minimum,
      :rush_rate_per_minute,
      :rush_rate_per_word,
      :specialization,
      :time_zone,
      :trados,
      :trados_version,
      :user_picture,
      :web_link,
      :zip_code,
      :avatar
      )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<div class="custom-notice"><%= notice %></div>
<div class="custom-alert"><%= alert %></div>

<!-- This is the beginning of the client view -->
<div class="container">
  <% if current_user.is_client %>
    <p>
      <%= link_to "Create New Project", new_project_path, :class => "btn btn-success" %>
    </p>
</div>
<!-- This is the client's Unassigned Projects table !-->

<div class="container">
  <h3>Unassigned Projects</h3>
  <table class="table table-striped table-responsive">
    <tr>
      <th>
        Name
      </th>
      <th>
        Type
      </th>
      <th>
        Proposed Budget
      </th>
      <th>
        Delivery Date
      </th>
      <th>
        Word Count
      </th>
      <th>
        Language Combination
      </th>
      <th>
      </th>
    </tr>
<% current_user.projects.each do |project| %>
  <% if !project.accepted_bid_id %>
    <tr>
      <td>
        <%= project.name %>
      </td>
      <td>
        <%= project.kind %>
      </td>
      <td>
        <%= project.budget %>
      </td>
      <td>
        <%= project.delivery_date %>
      </td>
      <td>
        <%= project.word_count %>
      </td>
      <td>
        <%= project.language_1 %> to <%= project.language_2 %>
      </td>
      <td>
        <%= link_to "See Current Bids", project_path(project), class: "btn btn-primary" %>
      </td>
    </tr>
  <% end %>
<% end %>
  <% if current_user.projects.select { |project|
    !project.accepted_bid_id }.count == 0 %>
    <tr>
      <td colspan=8>
        None currently
      </td>
    </tr>
  <% end %>
  </table>
</div>

<!-- This is the client's Projects In Progress Table -->
<div class="container">
  <h3>Projects In Progress</h3>
  <table class="table table-striped table-responsive">
    <tr>
      <th>
        Name
      </th>
      <th>
        Type
      </th>
      <th>
        Budget
      </th>
      <th>
        Delivery Date
      </th>
      <th>
        Word Count
      </th>
      <th>
        Language Combination
      </th>
      <th>
        Vendors Assigned
      </th>
      <th>
      </th>
    </tr>
    <% current_user.projects.each do |project| %>
      <% if project.accepted_bid_id && !project.completed_client %>
        <tr>
          <td>
            <%= project.name %>
          </td>
          <td>
            <%= project.kind %>
          </td>
          <td>
            <%= project.accepted_bid.budget %>
          </td>
          <td>
            <%= project.accepted_bid.delivery_date %>
          </td>
          <td>
            <%= project.word_count %>
          </td>
          <td>
            <%= project.language_1 %> to <%= project.language_2 %>
          </td>
          <td>
            <%= project.accepted_bid.f_name %> <%= project.accepted_bid.l_name %>
          </td>
          <td>
            <%= link_to "Check Project", project_path(project), class: "btn btn-success" %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <% if current_user.projects.select { |project|
      project.accepted_bid_id && !project.completed_client && !project.completed_vendor }.count == 0 %>
      <tr>
        <td colspan=8>
          None currently
        </td>
      </tr>
    <% end %>
  </table>
</div>

<!-- This is the client's Completed Projects table -->
<div class="container">
  <h3>Completed Projects</h3>
    <table class="table table-striped table-responsive">
      <tr>
        <th>
          Name
        </th>
        <th>
          Type
        </th>
        <th>
          Budget
        </th>
        <th>
          Date Completed
        </th>
        <th>
          Word Count
        </th>
        <th>
          Vendors
        </th>
        <th>
        </th>
      </tr>
<% current_user.projects.each do |project| %>
  <% if project.completed_client %>
      <tr>
        <td>
          <%= project.name %>
        </td>
        <td>
          <%= project.kind %>
        </td>
        <td>
          <%= project.accepted_bid.budget %>
        </td>
        <td>
          <%= project.accepted_bid.delivery_date %>
        </td>
        <td>
          <%= project.word_count %>
        </td>
        <td>
          <%= project.accepted_bid.f_name %> <%= project.accepted_bid.l_name %>
        </td>
        <td>
          <%= link_to "See Documents", project_path(project), class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  <% end %>
      <% if current_user.projects.select { |project|
        project.completed_client }.count == 0 %>
        <tr>
          <td colspan=7>
            None currently
          </td>
        </tr>
      <% end %>
  </table>
</div>
<% end %>
<!-- This is the end tag for the client view above !-->

<!-- This is the beginning of the translator/transcriber/graphic designer view !-->
<% if current_user.is_translator || current_user.is_transcriber || current_user.is_graphic_designer %>
  <div class="container">
    <%= link_to "Jobs Board", projects_path, class: "btn btn-success" %>
  </div>

<!--   This is the vendor's Active Bids table! -->
<div class="container">
    <h3>Active Bids</h3>
    <table class="table table-striped table-responsive">
      <tr>
        <th>
          Name
        </th>
        <th>
          Client
        </th>
        <th>
          Type
        </th>
        <th>
          Proposed budget
        </th>
        <th>
          Proposed delivery date
        </th>
        <th>
          Word Count
        </th>
        <th>
          Language Combination
        </th>
        <th>
        </th>
      </tr>
      <% current_user.bids.each do |bid| %>
        <% if !bid.project.accepted_bid_id %>
          <tr>
            <td>
              <%= bid.project.name %>
            </td>
            <td>
              <%= bid.project.user.f_name %> <%= bid.project.user.l_name %>
            </td>
            <td>
              <%= bid.project.kind %>
            </td>
            <td>
              <%= bid.budget %>
            </td>
            <td>
              <%= bid.delivery_date %>
            </td>
            <td>
              <%= bid.project.word_count %>
            </td>
            <td>
              <%= bid.project.language_1 %> to <%= bid.project.language_2 %>
            </td>
            <td>
              <%= link_to "See Project", project_path(bid.project), class: "btn btn-primary" %>
            </td>
          </tr>
        <% end %>
      <% end %>
      <% if current_user.bids.select { |bid|
        !bid.project.accepted_bid_id }.count == 0 %>
        <tr>
          <td colspan=8>
            None currently
          </td>
        </tr>
      <% end %>
      </table>
      </div>

<!-- This is the vendor's Projects In Progress table! -->
<div class="container">
  <h3>Projects In Progress</h3>
  <table class="table table-striped table-responsive">
    <tr>
      <th>
        Name
      </th>
      <th>
        Client
      </th>
      <th>
        Type
      </th>
      <th>
        Budget
      </th>
      <th>
        Delivery Date
      </th>
      <th>
        Word Count
      </th>
      <th>
        Language Combination
      </th>
      <th>
      </th>
    </tr>
    <% current_user.bids.each do |bid| %>
      <% if bid.accepted && !bid.project.completed_client %>
        <tr>
          <td>
            <%= bid.project.name %>
          </td>
          <td>
            <%= bid.project.user.f_name %> <%= bid.project.user.l_name %>
          </td>
          <td>
            <%= bid.project.kind %>
          </td>
          <td>
            <%= bid.budget %>
          </td>
          <td>
            <%= bid.delivery_date %>
          </td>
          <td>
            <%= bid.project.word_count %>
          </td>
          <td>
            <%= bid.project.language_1 %> to <%= bid.project.language_2 %>
          </td>
          <td>
            <%= link_to "Edit Details", project_path(bid.project), class: "btn btn-warning" %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <% if current_user.bids.select { |bid|
      bid.accepted && !bid.project.completed_client }.count == 0 %>
      <tr>
        <td colspan=8>
          None currently
        </td>
      </tr>
    <% end %>
  </table>
</div>

  <div class="container">
  <h3>Completed Projects</h3>
    <table class="table table-striped table-responsive">
      <tr>
        <th>
          Name
        </th>
        <th>
          Client
        </th>
        <th>
          Type
        </th>
        <th>
          Budget
        </th>
        <th>
          Date Completed
        </th>
        <th>
          Word Count
        </th>
      </tr>
  <% current_user.bids.each do |bid| %>
    <% if bid.project.completed_client && if bid.id == bid.project.accepted_bid_id %>
      <tr>
        <td>
          <%= bid.project.name %>
        </td>
        <td>
          <%= bid.project.user.f_name %> <%= bid.project.user.l_name %>
        </td>
        <td>
          <%= bid.project.kind %>
        </td>
        <td>
          <%= bid.project.budget %>
        </td>
        <td>
          <%= bid.project.delivery_date %>
        </td>
        <td>
          <%= bid.project.word_count %>
        </td>
      </tr>
    <% end %>
    <% end %>
  <% end %>
    <% if current_user.bids.select { |bid|
      bid.project.completed_client }.count == 0 %>
      <tr>
        <td colspan=7>
          None currently
        </td>
      </tr>
    <% end %>
    </table>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div><%= notice %></div>
  <div class="custom-alert"><%= alert %></div>
</div>

<div class="container">
<h2>Edit Your Profile</h2>

<%= form_for @user, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label "User Picture" %>
    </div>
    <div class="col-xs-6 field">
      <%= f.file_field :avatar %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :first_name %>
    </div>
    <div class="col-xs-6 field">
      <%= f.text_field :f_name %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :last_name %>
    </div>
    <div class="col-xs-6 field">
        <%= f.text_field :l_name %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :email %>
    </div>
    <div class="col-xs-6 field">
        <%= f.text_field :email %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :phone_number %>
    </div>
    <div class="col-xs-6 field">
        <%= f.text_field :phone_number %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :city %>
    </div>
    <div class="col-xs-6 field">
        <%= f.text_field :city %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :country %>
    </div>
    <div class="col-xs-6 field">
        <%= f.text_field :country %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :time_zone %>
    </div>
    <div class="col-xs-6 field">
      <%= time_zone_select(:user, :time_zone, ActiveSupport::TimeZone.us_zones, default: "Pacific Time (US & Canada)") %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :bio %>
    </div>
    <div class="col-xs-10 field">
        <%= f.text_area :bio %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :web_link %>
    </div>
    <div class="col-xs-6 field">
        <%= f.text_field :web_link %>
    </div>
  </div>
  <% if @user.is_client %>
    <div class="row">
      <div class="col-xs-2 field">
        <%= f.label :company %>
      </div>
      <div class="col-xs-6 field">
          <%= f.text_field :company %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 field">
        <%= f.label :position %>
      </div>
      <div class="col-xs-6 field">
          <%= f.text_field :position %>
      </div>
    </div>
  <% end %>
  <% if @user.is_translator %>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :language_pair %>
    </div>
    <div class="col-xs-6 field">
      <%= f.select :language_1, ['Arabic', 'Armenian, Western', 'Armenian, Eastern', 'Bengali', 'Bulgarian', 'Burmese', 'Cebuano', 'Chinese, Simplified',
        'Chinese, Traditional', 'Croatian', 'Czech', 'Danish', 'Dari', 'Dutch', 'English', 'Farsi', 'Finnish', 'French (Canadian)', 'French (Belgian)', 'French',
        'German', 'Greek', 'Hebrew', 'Hindi', 'Hungarian', 'Hmong', 'Indonesian', 'Italian', 'Japanese', 'Khmer', 'Korean', 'Norwegian', 'Polish',
        'Portuguese (Brazil)', 'Portuguese (European)', 'Punjabi', 'Russian', 'Spanish', 'Swedish', 'Tagalog', 'Thai', 'Turkish', 'Ukrainian',
        'Urdu', 'Vietnamese'] %> to
      <%= f.select :language_2, ['Arabic', 'Armenian, Western', 'Armenian, Eastern', 'Bengali', 'Bulgarian', 'Burmese', 'Cebuano', 'Chinese, Simplified',
        'Chinese, Traditional', 'Croatian', 'Czech', 'Danish', 'Dari', 'Dutch', 'English', 'Farsi', 'Finnish', 'French (Canadian)',
        'French (Belgian)', 'French', 'German', 'Greek', 'Hebrew', 'Hindi', 'Hungarian', 'Hmong', 'Indonesian', 'Italian', 'Japanese', 'Khmer',
        'Korean', 'Norwegian', 'Polish', 'Portuguese (Brazil)', 'Portuguese (European)', 'Punjabi', 'Russian', 'Spanish', 'Swedish', 'Tagalog',
        'Thai', 'Turkish', 'Ukrainian', 'Urdu', 'Vietnamese'] %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :rate_per_word %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :rate_per_word, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :minimum_rate %>
    </div>
    <div class="col-xs-6 field">
        <%= f.number_field :minimum_rate %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :rush_rate_per_word %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :rush_rate_per_word, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :rush_minimum %>
    </div>
    <div class="col-xs-6 field">
        <%= f.number_field :rush_minimum %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :notary_fee %>
    </div>
    <div class="col-xs-6 field">
        <%= f.number_field :notary_fee %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label :specialization %>
    </div>
    <div class="col-xs-6 field">
        <%= f.text_field :specialization %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "ATA Certified" %>
      <%= f.check_box :ata_certified %>
    </div>
    <div class="col-xs-3 field">
      <%= f.label "Judicial Court Certified" %>
      <%= f.check_box :judicial_court %>
    </div>
    <div class="col-xs-3 field">
      <%= f.label "Available Now?" %>
      <%= f.check_box :available %>
    </div>
    <div class="col-xs-3 field">
      <%= f.label "Use Trados?" %>
      <%= f.check_box :trados %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :trados_version %>
    </div>
    <div class="col-xs-6 field">
        <%= f.text_field :trados_version %>
    </div>
  </div>
  <% end %>
  <% if @user.is_transcriber %>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :rate_per_minute %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :rate_per_minute, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :rate_per_work_hour %>
    </div>
    <div class="col-xs-6 field">
    <%= f.number_field :rate_per_work_hour, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :rush_rate_per_minute %>
    </div>
    <div class="col-xs-6 field">
    <%= f.number_field :rush_rate_per_minute, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :minimum_rate %>
    </div>
    <div class="col-xs-6 field">
    <%= f.number_field :minimum_rate, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :rush_minimum %>
    </div>
    <div class="col-xs-6 field">
    <%= f.number_field :rush_minimum, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "Available Now?" %>
      <%= f.check_box :available %>
    </div>
  </div>
  <% end %>
  <% if @user.is_graphic_designer %>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label "Hourly Rate" %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :rate_per_work_hour, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
      <div class="col-xs-3 field">
        <%= f.label "Available Now?" %>
        <%= f.check_box :available %>
      </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label "Enter Password to Update Profile" %>
    </div>
    <div class="col-xs-6 field">
        <%= f.password_field :password %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label "Re-enter password" %>
    </div>
    <div class="col-xs-6 field">
        <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 actions">
      <%= f.submit "Update Profile", :class => "btn btn-success" %>
    </div>
  </div>
<% end %>
</div>

app/views/users/index.html.erb
<h1>Vendors</h1>

<div class="container">
  <h2>Translators</h2>
  <table class="table table-striped table-responsive">
    <tr>
      <th>
        Name
      </th>
      <th>
        Country
      </th>
      <th>
        Time Zone
      </th>
      <th>
        Language Combination
      </th>
      <th>
        Rate Per Word
      </th>
      <th>
        Minimum Rate
      </th>
      <th>
        Rush Rate Per Word
      </th>
      <th>
        Rush Minimum
      </th>
      <th>
        ATA Certified?
      </th>
      <th>
        Judicial Court
      </th>
      <th>
        Trados?
      </th>
      <th>
        Trados Version
      </th>
      <th>
        Available Now?
      </th>
      <th>
        Notary Fee
      </th>
    </tr>
  <% if @users.select { |user|
    user.is_translator? }.count == 0 %>
    <tr>
      <td colspan=13>
        <%= "None currently." %>
      </td>
    </tr>
  <% else %>
  <% @users.each do |user| %>
    <% if user.is_translator %>
      <tr>
        <td>
          <%= link_to user.f_name + " " + user.l_name, user_path(user) %>
        </td>
        <td>
          <%= user.country %>
        </td>
        <td>
          <%= user.time_zone %>
        </td>
        <td>
          <% if user.language_1.nil? || user.language_2.nil? %>
            <% else %>
              <%= user.language_1 %> to <%= user.language_2 %>
          <% end %>
        <td>
          <%= user.rate_per_word %>
        </td>
        <td>
          <%= user.minimum_rate %>
        </td>
        <td>
          <%= user.rush_rate_per_word %>
        </td>
        <td>
          <%= user.rush_minimum %>
        </td>
        <td>
          <% if user.ata_certified %>
            yes
          <% else %>
            no
          <% end %>
        </td>
        <td>
          <% if user.judicial_court %>
            yes
          <% else %>
            no
          <% end %>
        </td>
        <td>
          <% if user.trados %>
            yes
          <% else %>
            no
          <% end %>
        </td>
        <td>
          <%= user.trados_version %>
        </td>
        <td>
          <% if user.available %>
            yes
          <% else %>
            no
          <% end %>
        </td>
        <td>
          <%= user.notary_fee %>
        </td>
      </tr>
    <% end %>
    <% end %>
    <% end %>
  </table>


  <h2>Transcribers</h2>
  <table class="table table-striped table-responsive">
    <tr>
      <th>
        Name
      </th>
      <th>
        Country
      </th>
      <th>
        Time Zone
      </th>
      <th>
        Language Combination
      </th>
      <th>
        Rate Per Minute
      </th>
      <th>
        Rate Per Work Hour
      </th>
      <th>
        Minimum Rate
      </th>
      <th>
        Rush Rate Per Minute
      </th>
      <th>
        Rush Minimum
      </th>
      <th>
        Available Now?
      </th>
    </tr>
    <% if @users.select { |user|
      user.is_transcriber? }.count == 0 %>
      <tr>
        <td colspan=10>
          <%= "None currently." %>
        </td>
      </tr>
    <% else %>
    <% @users.each do |user| %>
      <% if user.is_transcriber %>
        <tr>
          <td>
            <%= user.f_name %> <% user.l_name %>
          </td>
          <td>
            <%= user.country %>
          </td>
          <td>
            <%= user.time_zone %>
          </td>
          <td>
            <% if user.language_1.nil? || user.language_2.nil? %>
              <% else %>
                <%= user.language_1 %> to <%= user.language_2 %>
            <% end %>
          </td>
          <td>
            <%= user.rate_per_minute %>
          </td>
          <td>
            <%= user.rate_per_work_hour %>
          </td>
          <td>
            <%= user.minimum_rate %>
          </td>
          <td>
            <%= user.rush_rate_per_minute %>
          </td>
          <td>
            <%= user.rush_minimum %>
          <td>
            <%= user.notary_fee %>
          </td>
        </tr>
      <% end %>
      <% end %>
      <% end %>
    </table>

    <h2>Graphic Designers</h2>
    <table class="table table-striped table-responsive">
      <tr>
        <th>
          Name
        </th>
        <th>
          Country
        </th>
        <th>
          Time Zone
        </th>
        <th>
          Rate Per Work Hour
        </th>
        <th>
          Available Now?
        </th>
      </tr>
      <% if @users.select { |user|
        user.is_graphic_designer? }.count == 0 %>
        <tr>
          <td>
            <%= "None currently." %>
          </td>
          <td>
          </td>
          <td>
          </td>
          <td>
          </td>
          <td>
          </td>
        </tr>
      <% else %>
      <% @users.each do |user| %>
        <% if user.is_transcriber %>
          <tr>
            <td>
              <%= user.f_name %> <% user.l_name %>
            </td>
            <td>
              <%= user.country %>
            </td>
            <td>
            </td>
            <td>
              <%= user.rate_per_work_hour %>
            </td>
              <% if user.available %>
                yes
              <% else %>
                no
              <% end %>
            </td>
          </tr>
        <% end %>
        <% end %>
        <% end %>
      </table>