config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "welcome#index"

  resources :users, except: [:index, :edit]

  resources :projects do
    resources :bids end

  resources :sessions, only: [:new, :create, :destroy]

  patch "/bids/:id/complete", to: "bids#complete"
  patch "/projects/:id/completeclient", to: "projects#completeclient"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#dashboard"
  # get "/accounts", to: "users#show"
  get "/accounts/edit", to: "users#edit"
  get "/vendors", to: "users#index"
  get "/contact", to: "welcome#contact"
  # get "/vendor/:id", to: "users#show"

  # get "/jobs", to: "jobs#index"

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_attached_file :document
  validates_attachment :document, content_type: { content_type: "application/pdf" }

  has_attached_file :completed_document
  validates_attachment :completed_document, content_type: { content_type: "application/pdf" }

  has_many :bids, dependent: :destroy

  # has_one :vendor,
  #   class_name: "User"

  def accepted_bid
    Bid.find(accepted_bid_id) if accepted_bid_id
  end

  def assigned_vendor
    User.find(vendor_id) if vendor_id
  end

  def needs
    output_arr = []
    output = ""
    output_arr.push("need translator") if need_translator
    output_arr.push("need transcriber") if need_transcriber
    output_arr.push("need graphic designer") if need_graphic_designer
    output_arr.push("need notarization") if need_notarization
    if output_arr.length > 1
      output_arr.each do |string, index|
        if index == output_arr.length-1
          output += string
        else
          output += string + ", "
        end
      end
    else
      output = output_arr[0]
    end
    return output
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @bids = @project.bids
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      redirect_to dashboard_path
      flash[:notice] = "You created a new project!"
    else
      render :new
      flash[:notice] = "Incomplete fields."
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to dashboard_path
      flash[:notice] = "You've updated this project!"
    else
      render :edit
      flash[:notice] = "Incomplete fields."
    end
  end

  def completeclient
    @project = Project.find(params[:id])
    @project.completed_client = true
    if @project.save(validate: false)
      flash[:notice] = "You've marked this completed!"
      redirect_to dashboard_path
    else
      flash[:notice] = "Unable to mark completed."
      render :show
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to dashboard_path
  end

private

  def project_params
    params.require(:project).permit(
      :accepted_bid_id,
      :assigned,
      :budget,
      :completed,
      :completed_client,
      :completed_document,
      :completed_vendor,
      :delivery_date,
      :document,
      :kind,
      :language_1,
      :language_2,
      :minutes_in_file,
      :name,
      :need_graphic_designer,
      :need_notarization,
      :need_transcriber,
      :need_translator,
      :sample_text,
      :special_request,
      :word_count,
      :vendor_id
      )
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="container">
<h3>Edit details for <%= @project.name %></h3>

<div class="alert alert-info" role="alert"><%= notice %></div>

<%= form_for @project do |f| %>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :name %>
    </div>
    <div class="col-xs-6 field">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :type %>
    </div>
    <div class="col-xs-6 field">
      <%= f.select :kind, ['Legal', 'Business', 'Medical', 'Technical', 'Educational', 'Personal', 'General']%>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :language_combination %>
    </div>
    <div class="col-xs-6 field">
      <%= f.select :language_1, ['Arabic', 'Armenian, Western', 'Armenian, Eastern', 'Bengali', 'Bulgarian', 'Burmese', 'Cebuano', 'Chinese, Simplified',
        'Chinese, Traditional', 'Croatian', 'Czech', 'Danish', 'Dari', 'Dutch', 'English', 'Farsi', 'Finnish', 'French (Canadian)', 'French (Belgian)', 'French',
        'German', 'Greek', 'Hebrew', 'Hindi', 'Hungarian', 'Hmong', 'Indonesian', 'Italian', 'Japanese', 'Khmer', 'Korean', 'Norwegian', 'Polish',
        'Portuguese (Brazil)', 'Portuguese (European)', 'Punjabi', 'Russian', 'Spanish', 'Swedish', 'Tagalog', 'Thai', 'Turkish', 'Ukrainian',
        'Urdu', 'Vietnamese'] %> to
      <%= f.select :language_2, ['Arabic', 'Armenian, Western', 'Armenian, Eastern', 'Bengali', 'Bulgarian', 'Burmese', 'Cebuano',
        'Chinese, Simplified', 'Chinese, Traditional', 'Croatian', 'Czech', 'Danish', 'Dari', 'Dutch', 'Farsi', 'Finnish',
        'French (Canadian)', 'French (Belgian)', 'French', 'German', 'Greek', 'Hebrew', 'Hindi', 'Hungarian', 'Hmong', 'Indonesian',
        'Italian', 'Japanese', 'Khmer', 'Korean', 'Norwegian', 'Polish', 'Portuguese (Brazil)', 'Portuguese (European)',
        'Punjabi', 'Russian', 'Spanish', 'Swedish', 'Tagalog', 'Thai', 'Turkish', 'Ukrainian', 'Urdu', 'Vietnamese'] %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :proposed_budget %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :budget, :class => 'text_field', :step => 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :proposed_delivery_date %>
    </div>
    <div class="col-xs-6 field">
      <%= f.date_select :delivery_date, :order => [:month, :day, :year] %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label "Need Translator?" %>
      <%= f.check_box :need_translator %>
    </div>
    <div class="col-xs-3 field">
      <%= f.label "Need Transcriber?" %>
      <%= f.check_box :need_transcriber %>
    </div>
    <div class="col-xs-3 field">
      <%= f.label "Need Graphic Designer?" %>
      <%= f.check_box :need_graphic_designer %>
    </div>
    <div class="col-xs-3 field">
      <%= f.label "Need Notarization?" %>
      <%= f.check_box :need_notarization %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :word_count %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :word_count, :class => 'text_field', :step => 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :minutes_in_file %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :minutes_in_file, :class => 'text_field', :step => 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :special_request %>
    </div>
    <div class="col-xs-6 field">
      <%= f.text_field :special_request %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :sample_text %>
    </div>
    <div class="col-xs-6 field">
      <%= f.text_field :sample_text %>
    </div>
  </div>
    <div class="actions"><%= f.submit %></div>
<% end %>
</div>

app/views/projects/index.html.erb
<div class="custom-notice"><%= notice %></div>
<div class="custom-alert"><%= alert %></div>
<div class="container">
<h3>Jobs Board</h3>
<table class="table table-hover table-striped table-responsive">
  <tr>
    <th>
      Client
    </th>
    <th>
      Project
    </th>
    <th>
      Type
    </th>
    <th>
      Proposed Budget
    </th>
    <th>
      Proposed delivery date
    </th>
    <th>
      Word Count
    </th>
    <th>
      Language Combination
    </th>
    <th>
      Needs
    </th>
    <th>
    </th>
  </tr>
    <% @projects.each do |project| %>
      <% if !project.accepted_bid_id %>
    <tr>
      <td>
        <%= project.user.f_name %> <%= project.user.l_name %>
      </td>
      <td>
        <%= project.name %>
      </td>
      <td>
        <%= project.kind %>
      </td>
      <td>
        <%= project.budget %>
      </td>
      <td>
        <%= project.delivery_date %>
      </td>
      <td>
        <%= project.word_count %>
      </td>
      <td>
        <%= project.language_1 %> to <%= project.language_2 %>
      </td>
      <td>
        <%= project.needs %>
      </td>
      <td>
        <%= link_to "See Current Bids", project_path(project), class: "btn btn-primary" %>
      </td>
    </tr>
    <% end %>
    <% end %>
</table>

app/views/projects/new.html.erb
<div class="container">
<h2>Create New Project</h2>

<div class="custom-alert"><%= notice %></div>

<%= form_for @project do |f| %>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :name %>
    </div>
    <div class="col-xs-6 field">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :type %>
    </div>
    <div class="col-xs-6 field">
      <%= f.select :kind, ['Legal', 'Business', 'Medical', 'Technical', 'Educational', 'Personal', 'General']%>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :language_combination %>
    </div>
    <div class="col-xs-6 field">
      <%= f.select :language_1, ['Arabic', 'Armenian, Western', 'Armenian, Eastern', 'Bengali', 'Bulgarian', 'Burmese', 'Cebuano', 'Chinese, Simplified',
        'Chinese, Traditional', 'Croatian', 'Czech', 'Danish', 'Dari', 'Dutch', 'English', 'Farsi', 'Finnish', 'French (Canadian)', 'French (Belgian)', 'French',
        'German', 'Greek', 'Hebrew', 'Hindi', 'Hungarian', 'Hmong', 'Indonesian', 'Italian', 'Japanese', 'Khmer', 'Korean', 'Norwegian', 'Polish',
        'Portuguese (Brazil)', 'Portuguese (European)', 'Punjabi', 'Russian', 'Spanish', 'Swedish', 'Tagalog', 'Thai', 'Turkish', 'Ukrainian',
        'Urdu', 'Vietnamese'] %> to
      <%= f.select :language_2, ['Arabic', 'Armenian, Western', 'Armenian, Eastern', 'Bengali', 'Bulgarian', 'Burmese', 'Cebuano',
        'Chinese, Simplified', 'Chinese, Traditional', 'Croatian', 'Czech', 'Danish', 'Dari', 'Dutch', 'English', 'Farsi', 'Finnish',
        'French (Canadian)', 'French (Belgian)', 'French', 'German', 'Greek', 'Hebrew', 'Hindi', 'Hungarian', 'Hmong', 'Indonesian',
        'Italian', 'Japanese', 'Khmer', 'Korean', 'Norwegian', 'Polish', 'Portuguese (Brazil)', 'Portuguese (European)',
        'Punjabi', 'Russian', 'Spanish', 'Swedish', 'Tagalog', 'Thai', 'Turkish', 'Ukrainian', 'Urdu', 'Vietnamese'] %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :proposed_budget %>
    </div>
    <div class="col-xs-6 field">
      <%= f.number_field :budget, class: "text_field", step: 0.01 %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :proposed_delivery_date %>
    </div>
    <div class="col-xs-6 field">
      <%= f.date_select :delivery_date, :order => [:month, :day, :year] %>
    </div>
  </div>
  <div class="row">
      <div class="col-xs-3 field">
        <%= f.label "Need Translator?" %>
        <%= f.check_box :need_translator %>
      </div>
      <div class="col-xs-3 field">
        <%= f.label "Need Transcriber?" %>
        <%= f.check_box :need_transcriber %>
      </div>
      <div class="col-xs-3 field">
        <%= f.label "Need Graphic Designer?" %>
        <%= f.check_box :need_graphic_designer %>
      </div>
      <div class="col-xs-3 field">
        <%= f.label "Need Notarization?" %>
        <%= f.check_box :need_notarization %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 field">
        <%= f.label :word_count %>
      </div>
      <div class="col-xs-6 field">
        <%= f.number_field :word_count, class: "text_field", step: 0.01 %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2 field">
        <%= f.label :minutes_in_file %>
      </div>
      <div class="col-xs-6 field">
        <%= f.number_field :minutes_in_file, class: "text_field", step: 0.01 %>
      </div>
    </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :special_request %>
    </div>
    <div class="col-xs-6 field">
      <%= f.text_area :special_request %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :sample_text %>
    </div>
    <div class="col-xs-6 field">
      <%= f.text_area :sample_text %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 field">
      <%= f.label :document %>
    </div>
    <div class="col-xs-6 field">
      <%= f.file_field :document %>
    </div>
  </div>
  <div class="actions"><%= f.submit "Create Project", :class => "btn btn-primary" %></div>
<% end %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <h2><%= @project.name %></h2>
</div>
<!-- This is for Active Bids !-->

<% if !@project.accepted_bid_id %>
  <div class="container">
    <div class="row">
      <h3>Proposal:</h3>
    </div>
    <div class="row">
      <strong>Budget: </strong><%= @project.budget %> USD
    </div>
    <div class="row">
      <strong>Delivery Date: </strong><%= @project.delivery_date %>
    </div>
    <div class="row">
      <strong>Word Count:</strong> <%= @project.word_count %>
    </div>
    <div class="row">
      <strong>Language Combination:</strong> <%= @project.language_1 %> to <%= @project.language_2 %>
    </div>
    <div class="row">
      <% if @project.document_file_name %>
        <%= link_to "Download Source Document", @project.document.url(:original, false), target: "_blank", class: "btn btn-primary" %>
       &nbsp;&nbsp;
     <% end %>
      <% if @project.user_id == current_user.id %>
        <%= link_to "Edit Project", edit_project_path, class: "btn btn-warning" %>
        &nbsp;&nbsp;
        <%= link_to "Delete Project", project_path, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
      <% end %>
    </div>
  </div>
  <div class="container">
    <h3>Current Bids</h3>
    <table class="table table-striped table-responsive">
    <tr>
      <th>
        Vendor Name
      </th>
      <th>
        Proposed Delivery Date
      </th>
      <th>
        Proposed budget
      </th>
      <th>
        Message
      </th>
      <th>
      </th>
    </tr>
  <% @bids.each do |bid| %>
  <tr>
    <td>
      <%= bid.user.f_name %> <%= bid.user.l_name %>
    </td>
    <td>
      <%= bid.delivery_date %>
    </td>
    <td>
      <%= bid.budget %>
    </td>
    <td>
      <%= bid.message %>
    </td>
    <td>
      <% if bid.user_id == current_user.id %>
        <%= link_to "Manage Your Bid", edit_project_bid_path(@project, bid), class: "btn btn-primary" %>
      <% end %>
      <% if @project.user_id == current_user.id %>
        <%= link_to "See Profile", user_path(bid.user), class: "btn btn-primary" %>
        <%= button_to "Accept", "/bids/#{bid.id}/complete", method: :patch, class: "btn btn-success" %>
      <% end %>
    </td>
  </tr>
  <% end %>
  <% if @bids.empty? %>
    <tr>
      <td colspan=8>
        None currently
      </td>
    </tr>
  <% end %>
</table>
<% if current_user.is_translator || current_user.is_transcriber || current_user.is_graphic_designer %>
  <%= link_to "Make Bid", new_project_bid_path(@project), class: "btn btn-success" %>
<% end %>
</div>

<% end %>
<!-- This is the end of active bids -->

<!-- This is the beginning of the client's view -->
 <!-- This is the client's view for Projects In Progress/Completed -->

<% if @project.accepted_bid_id && current_user.id == @project.user_id %>
  <div class="container">
  <% if @project.completed_document_file_name %>
    <p><%= link_to "See Translated Document", @project.completed_document.url(:original, false), target: "_blank", class: "btn btn-default" %></p>
  <% else %>
    Vendor has not yet uploaded anything.
  <% end %>
  </div>
<!-- This is the client's view for Projects if not completed yet !-->
<% if @project.accepted_bid_id && !@project.completed_client %>
<div class="container">
  <%= link_to "See Source", @project.document.url(:original, false), target: "_blank", class: "btn btn-primary" %>
  <%= button_to "Mark Completed", "/projects/#{@project.id}/completeclient", method: :patch, class: "btn btn-success" %>
  </div>
<% end %>
<% end %>
<!-- This is the end of the client's view !-->

<!-- This is the beginning of the translator's view !-->

<% if @project.accepted_bid_id && current_user.id == @project.vendor_id %>
  <div class="container">
  <%= form_for @project, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-3 field">
      <%= f.label :upload_completed_document %>
    </div>
    <div class="col-xs-6 field">
      <%= f.file_field :completed_document %>
    </div>
  </div>
    <div class="actions">
        <% if @project.completed_document_file_name %>
          <p><%= link_to "See Uploaded Translation", @project.completed_document.url(:original, false), target: "_blank", class: "btn btn-default" %></p>
        <% end %>
        <%= link_to "See Source", @project.document.url(:original, false), target: "_blank", class: "btn btn-primary" %>
        <%= f.submit "Update Project", class: "btn btn-success" %></div>
  </div>
<% end %>
<% end %>