config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "welcome#index"

  resources :users, except: [:index, :edit]

  resources :projects do
    resources :bids end

  resources :sessions, only: [:new, :create, :destroy]

  patch "/bids/:id/complete", to: "bids#complete"
  patch "/projects/:id/completeclient", to: "projects#completeclient"

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#dashboard"
  # get "/accounts", to: "users#show"
  get "/accounts/edit", to: "users#edit"
  get "/vendors", to: "users#index"
  get "/contact", to: "welcome#contact"
  # get "/vendor/:id", to: "users#show"

  # get "/jobs", to: "jobs#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <title>TranslateAppV1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="jumbotron">
      FOLIO
    </div>
    <nav class="navbar navbar-inverse">
      <div>
    <% if current_user %>
        <ul class="navbar-nav">
          <li class="greeting inline-nav">
            Welcome, <%= current_user.f_name %>
          </li>
          <li class="inline-nav">
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to "Account", accounts_edit_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
          </li>
          <li class="inline-nav">
            <%= link_to "Dashboard", dashboard_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
          </li>
        <% if current_user.is_client %>
          <li class="inline-nav">
            <%= link_to "Vendors", vendors_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
          </li>
        <% end %>
        <% if current_user.is_translator %>
          <li class="inline-nav">
            <%= link_to "Jobs", projects_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
          </li>
      <% end %>
          <li class="inline-nav">
            <%= link_to "Contact", contact_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
          </li>
      <!-- session_path leads to sessions#destroy-->
          <li class="inline-nav">
            <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
          </li>
        </ul>
    <% else %>
    <ul class="navbar-nav">
      <li class="inline-nav">
        <%= link_to 'Log In', login_path %>
         &nbsp;&nbsp;|&nbsp;&nbsp;
      </li>
      <li class="inline-nav">
        <%= link_to 'Sign Up', new_user_path %>
      </li>
    </ul>
    <% end %>
    </div>
    </nav>
    <%= yield %>
  </body>
</html>